Repository oamg/leapp, pull requests merged in 2019-04, with the labels that each got.

#475 Update title of the readthedocs
  docs/source/index.rst
Labels: documentation

#477 Add return codes to man page
  man/leapp.1
Labels: documentation

#478 stdlib: _call: Ignore the linebuffer
  leapp/libraries/stdlib/call.py
  tests/scripts/test_stdlib_call.py
Labels: bug

#485 stdlib: Py 2 and 3 compatible __logging_handler
  leapp/libraries/stdlib/__init__.py
Labels: bug

#486 Use realpath when load actors?
  leapp/actors/__init__.py
Labels: bug, question

#489 Temporary fix of leapp.stdlib
  leapp/libraries/stdlib/__init__.py
  leapp/libraries/stdlib/call.py
Labels: bug

#493 Changes to archive and create logs structure
  .github/ISSUE_TEMPLATE/bug_report.md
  leapp/cli/upgrade/__init__.py
  leapp/logger/__init__.py
Labels: For GA
