Repository oamg/leapp, pull requests merged in 2019-01, with the labels that each got.

#401 Update RepositoryManager class comments
  leapp/repository/manager.py
Labels: docs

#417 Update link to homepage in README
  README.md
Labels: docs

#405 stdlib: Actor API convenience library
  leapp/actors/__init__.py
  leapp/libraries/stdlib/api.py
  leapp/snactor/fixture.py
  tests/data/actor-api-tests/.leapp/info
  tests/data/actor-api-tests/.leapp/leapp.conf
  tests/data/actor-api-tests/actors/first/actor.py
  tests/data/actor-api-tests/actors/first/files/directory/first-actor
  tests/data/actor-api-tests/actors/first/files/duplicate
  tests/data/actor-api-tests/actors/second/actor.py
  tests/data/actor-api-tests/actors/second/files/directory/second-actor
  tests/data/actor-api-tests/actors/second/files/duplicate
  tests/data/actor-api-tests/files/directory/repository
  tests/data/actor-api-tests/files/duplicate
  tests/data/actor-api-tests/models/apitest.py
  tests/data/actor-api-tests/tags/actorfileapi.py
  tests/data/actor-api-tests/topics/apitest.py
  tests/scripts/test_actor_api.py
Labels: wip

#424 Add metapackage for dependencies
  packaging/leapp.spec
Labels: enhancement
