Repository oamg/leapp, pull requests merged in 2019-06, with the labels that each got.

#518 [WIP][TO BE UPDATED] lint: make linter more strict
  .pylintrc
  leapp/actors/__init__.py
  leapp/cli/upgrade/__init__.py
  leapp/compatpy2only/__init__.py
  leapp/dialogs/renderer.py
  leapp/repository/__init__.py
  leapp/repository/actor_definition.py
  leapp/snactor/commands/new_actor.py
  leapp/snactor/fixture.py
  leapp/snactor/utils.py
  leapp/utils/meta.py
  leapp/utils/repository.py
  leapp/workflows/tagfilters.py
  tests/scripts/test_actor_api.py
  tests/scripts/test_phaseactors.py
  tests/scripts/test_serialization.py
Labels: wip

#500 Add documentation of how to write an actor to upgrade process.
  docs/source/actor-rhel7-to-rhel8.md
  docs/source/tutorials.rst
Labels: docs, documentation

#508 Redirect from github.io to RTD
  _config.yml
  _layouts/default.html
  actors.md
  architecture.md
  css/bulma.min.css
  gettingstarted.md
  img/arch-big-picture.png
  img/framework-arch-overview.png
  img/leapp-logo.png
  img/leapp-logo.svg
  img/leapp-sequence-diagram.png
  img/phases.png
  index.html
  index.md
  upgrades.md
Labels: docs, documentation

#526 Add links to resources not included in RTD
  docs/source/index.rst
  docs/source/pydoc/leapp.reporting.rst
Labels: documentation

#525 fixtures: introduce conftest.py
  tests/scripts/conftest.py
  tests/scripts/helpers.py
  tests/scripts/test_messaging.py
  tests/scripts/test_repository.py
  tests/scripts/test_repository_actor_definition.py
  tests/scripts/test_snactor.py
  tests/scripts/test_utils_project.py
Labels: proposal

#505 Create dynamic configuration phase
  leapp/actors/__init__.py
  leapp/exceptions.py
  leapp/messaging/__init__.py
  leapp/messaging/inprocess.py
  leapp/messaging/remote.py
  leapp/messaging/testing.py
  leapp/repository/actor_definition.py
  leapp/workflows/__init__.py
  leapp/workflows/tagfilters.py
  tests/data/workflow-tests/actors/configprovider/actor.py
  tests/data/workflow-tests/actors/firstactor/actor.py
  tests/data/workflow-tests/models/unittestconfig.py
  tests/data/workflow-tests/topics/config.py
  tests/data/workflow-tests/workflows/unit_test.py
  tests/scripts/test_workflow.py
Labels: enhancement
