Repository oamg/leapp, pull requests merged in 2019-03, with the labels that each got.

#454 Fix docstrings
  leapp/libraries/stdlib/__init__.py
  leapp/libraries/stdlib/call.py
Labels: documentation

#446 Documentation for metapackages dependencies
  docs/source/dependencies.md
Labels: documentation

#464 stdlib: Functions to check the current config
  leapp/libraries/stdlib/config.py
  tests/scripts/test_stdlib.py
Labels: enhancement

#465 leapp: Fix debug/verbose restore on resume
  leapp/cli/upgrade/__init__.py
Labels: bug

#463 clicmd: Add support for tools without subcommands
  leapp/utils/clicmd.py
Labels: enhancement
